docs: update descriptions in schema
team-apm/apm-schema pull request #150
Opened 2024-01-06 17:52 UTC by mitosagi

## Description

Update the description in `packages.json` to the latest content. Also, make description clearer and less ambiguous to allow AI editing.

## Related Issue

This PR depends on the following PR(s)
- #149

## How Has This Been Tested?

## Checklist:

2024-02-06 23:45 UTC, hal-shu-sato requested changes
Very good descriptions but there is a typo.

2024-02-06 23:45 UTC, hal-shu-sato commented on v3/schema/packages.json
> +            "description": "The latest version of the package. If not available, file update date (YYYYY/MM/DD)."
typo
```suggestion
            "description": "The latest version of the package. If not available, file update date (YYYY/MM/DD)."
```

2024-02-14 14:24 UTC, mitosagi commented on v3/schema/packages.json
> +            "description": "The latest version of the package. If not available, file update date (YYYYY/MM/DD)."
Thanks for confirming. Fixed.

2024-02-19 17:05 UTC, hal-shu-sato approved these changes

2024-02-19 17:05 UTC, merged